"""empty message

Revision ID: 02486925699d
Revises: 1c9334ab9aaa
Create Date: 2021-05-19 10:14:39.976714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02486925699d'
down_revision = '1c9334ab9aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startsat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_no', sa.Integer(), nullable=True),
    sa.Column('station_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_no'], ['station.id'], ),
    sa.ForeignKeyConstraint(['train_no'], ['train.train_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stopsat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_no', sa.Integer(), nullable=True),
    sa.Column('station_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_no'], ['station.id'], ),
    sa.ForeignKeyConstraint(['train_no'], ['train.train_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('stopsat')
    op.drop_table('startsat')
    op.drop_table('station')
    op.drop_table('cancellation')
    # ### end Alembic commands ###
