"""empty message

Revision ID: 1c9334ab9aaa
Revises: 53d4f83ae020
Create Date: 2021-05-19 09:52:50.774786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9334ab9aaa'
down_revision = '53d4f83ae020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('a_seats2', sa.Integer(), nullable=True),
    sa.Column('fare1', sa.Integer(), nullable=True),
    sa.Column('fare2', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('w_seat1', sa.Integer(), nullable=True),
    sa.Column('w_seats2', sa.Integer(), nullable=True),
    sa.Column('b_seats1', sa.Integer(), nullable=True),
    sa.Column('b_seats2', sa.Integer(), nullable=True),
    sa.Column('a_seats1', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['train.train_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_status')
    # ### end Alembic commands ###
