"""empty message

Revision ID: 53d4f83ae020
Revises: 
Create Date: 2021-05-19 09:38:55.703984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d4f83ae020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train',
    sa.Column('train_no', sa.Integer(), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=True),
    sa.Column('arrival_time', sa.String(length=100), nullable=True),
    sa.Column('departure_time', sa.String(length=100), nullable=True),
    sa.Column('no_Seats_available', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('train_no')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('aadhar', sa.String(length=12), nullable=True),
    sa.Column('mobile_number', sa.String(length=10), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_aadhar'), ['aadhar'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_mobile_number'), ['mobile_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('no_of_passenger', sa.Integer(), nullable=True),
    sa.Column('train_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['train_no'], ['train.train_no'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passenger',
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('pnr_no', sa.String(length=80), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('reservation_status', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passenger_pnr_no'), ['pnr_no'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passenger_pnr_no'))

    op.drop_table('passenger')
    op.drop_table('ticket')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_aadhar'))

    op.drop_table('user')
    op.drop_table('train')
    # ### end Alembic commands ###
